image: debian/testing

secrets:
  - 461a6f42-6635-415f-9533-b7f11adf4779

packages:
  - nodejs
  - npm

sources:
  - git+ssh://git@git.sr.ht/~klahr/quadrate-vscode

environment:
  GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"

tasks:
  - build: |
      cd quadrate-vscode
      npm install
      npm run compile

triggers:
  - action: email
    condition: failure
    to: klahr@r8.rs
